version: '3'

networks:
  app_net:
    driver: bridge
  videos_net:
    driver: bridge

services:
  usuarios:
    build: ./usuarios
    ports:
      - "3000:3000"
    environment:
      DB_NAME: monitor_usuarios
      DB_HOST: usuarios_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      FLASK_APP: ./src/main.py
    depends_on:
      - usuarios_db
    networks:
      - app_net

  usuarios_db:
    image: postgres
    environment:
      POSTGRES_DB: monitor_usuarios
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
    networks:
      - app_net
